name: containers (all branches)
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 12 * * *'

jobs:
  cron_build:
    secrets: inherit
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        fedora_branch: ['42', '43', 'rawhide']
    uses: ./.github/workflows/containers.yml
    with:
      fedora_branch: ${{ matrix.fedora_branch }}
