name: containers (all branches)
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * *'

jobs:
  main:
    secrets: inherit
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        fedora_branch: ['43']
    uses: ./.github/workflows/containers.yml
    with:
      fedora_branch: ${{ matrix.fedora_branch }}
      device: fairphone-fp5
      xiaomi_nabu_samsung_ufs: false
  # nabu_samsung:
  #   if: ${{ github.event_name != 'schedule' || !github.event.repository.fork }}
  #   secrets: inherit
  #   permissions:
  #     packages: write
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       fedora_branch: ['42', '43', 'rawhide']
  #   uses: ./.github/workflows/containers.yml
  #   with:
  #     fedora_branch: ${{ matrix.fedora_branch }}
  #     device: xiaomi-nabu
  #     target_tag_override: ${{ matrix.fedora_branch }}-samsung
  #     xiaomi_nabu_samsung_ufs: true
