on:
  workflow_call:
    inputs:
      esp_size:
        required: true
        type: number
      device:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        type: string
        default: '42'
      rootfs:
        type: string
        default: btrfs
      args_7z:
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Clone the repository
      uses: actions/checkout@v4

    - name: Raw disk image
      id: build-raw
      uses: osbuild/bootc-image-builder-action@v0.0.2
      with:
        config-file: ./config.toml
        image: ${{ vars.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
        rootfs: ${{ inputs.rootfs }}
        types: |
          raw

    - name: Post-process image artifacts
      env:
        DEVICE: ${{ inputs.device }}
        IMAGE_NAME: ${{ inputs.image_name }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        ESP_SIZE: ${{ inputs.esp_size }}
        ARGS_7Z: ${{ inputs.args_7z}}
        OUTPUT_DIR: ${{ steps.build-raw.outputs.output-directory }}
      run: |
        curl -L https://7-zip.org/a/7z2501-linux-arm64.tar.xz | tar -xJf -
        sudo cp 7zzs /bin/7z
        bash scripts/build_image.sh
        bash scripts/$DEVICE/artifacts_$DEVICE.sh
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pocketblue-${{ inputs.image_name }}-${{ inputs.image_tag }}
        path: ./pocketblue-${{ inputs.image_name }}-${{ inputs.image_tag }}.7z
        compression-level: 0
